# Generated by Django 4.1.2 on 2022-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_alter_photo_height_alter_photo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
