# Generated by Django 4.1.2 on 2022-10-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_photo_image_url_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/%Y/%m/%d', width_field='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
