# Generated by Django 4.1.2 on 2022-10-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0005_alter_photo_height_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dominant_color',
        ),
    ]
