# Generated by Django 4.1.2 on 2022-10-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_remove_photo_dominant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
