# Generated by Django 4.1.2 on 2022-10-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0007_photo_dominant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dominant_color',
        ),
    ]
