# Generated by Django 4.1.2 on 2022-10-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0009_photo_dominant_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_url',
            new_name='url',
        ),
    ]
