# Generated by Django 4.1.2 on 2022-10-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0010_rename_image_url_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
    ]
